### ISSUE TITLE
Administrator e-mail to specific e-mail address

### ISSUE THREAD

**Issue by FranklinKramer** [JOOlanders/newdocs#27]
Hey there,

How can I arrange that the Administrator New Order e-mail is sent only to one specific mail address (webshop@example.com) rather than to the mail address of the Administrator?

Regards,
Franklin

**Comment by dguzenko** [comment]
Hello Franklin,

In the email settings (Components / ZOOlanders / ZOOcart tab / Settings / Emails / Email Template button) you can specify the email address(es) to send a copy (Carbon Copy or Blind Carbon Copy) of each email. 

Please let me know if it will work for you?
