### ISSUE TITLE
Weight and/or size dimensions vs shipping rates

### ISSUE THREAD

**Issue by FranklinKramer** [JOOlanders/newdocs#28]
I know that it is possible to use dimensions like weight in order to choose a shipping rate. Where and how do I set these products weights in a product view in order for the cart to recognize it as product weight?

**Comment by dguzenko** [comment]
Hi Franklin,

Add the "Measures Pro" element to the type and set measuring units in "Unit" param (for example kg) . In the item configuration you can specify the dimension in your measuring units (for example "2", so 1 item weight is 2 kg). This measure will be used for shipping rates.
